name: build
on:
  pull_request:
  push:
    branches: [ rolling ]
  workflow_dispatch:
env:
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image: ['ros:iron-ros-base', 'ros:rolling-ros-base']
    container:
      image: ${{ matrix.docker_image }}
    timeout-minutes: 30
    steps:
    - name: Deps
      run: |
        apt update && apt install -y curl
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@1.75.0
    - uses: actions/checkout@v2
    - name: Clone system_tests
      run: |
        git clone https://github.com/ros2/system_tests.git
    - name: rosdep
      run: |
        rosdep update
        rosdep install --from-paths . -yir
    - name: build
      run: /ros_entrypoint.sh colcon build --packages-up-to rmw_zenoh_cpp test_rclcpp
    - name: test
      run: |
        source install/setup.bash
        /ros_entrypoint.sh launch_test rmw_zenoh_cpp/test/test_rclcpp_launch.py
